version: "3"
services:
  book-app-api:
    restart: unless-stopped
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      FRONTEND_ALLOWED_HOSTS: ${FRONTEND_ALLOWED_HOSTS}